services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - ./db:/var/lib/postgresql/data
  
  redis:
    image: redis
    restart: unless-stopped
  
  web:
    build:
      context: .
      dockerfile: docker/server
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/db
      - REDIS_URL=redis://redis:6379/0
      - HUEY_IMMEDIATE=False
    command: python manage.py runserver 0.0.0.0:8000
  
  task-runner:
    build:
      context: .
      dockerfile: docker/server
    depends_on:
      - db
      - redis
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/db
      - REDIS_URL=redis://redis:6379/0
      - HUEY_IMMEDIATE=False
    command: python manage.py run_huey
  
  webui:
    build:
      context: .
      dockerfile: docker/webui
    ports:
      - "3000:3000"
    volumes:
      - ./webui:/usr/src/app