# Generated by Django 4.1.3 on 2022-11-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="blurhash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
